# Generated by Django 3.1.3 on 2020-12-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('shop', models.CharField(blank=True, max_length=300, null=True)),
                ('brand', models.CharField(blank=True, max_length=300, null=True)),
                ('product', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
                ('img', models.CharField(blank=True, max_length=2000, null=True)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'crawled_data',
                'managed': False,
            },
        ),
    ]
